# Generated by Django 4.1.3 on 2023-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('internation', 'International'), ('tech', 'Technology'), ('politics', 'Politics')], default='tech', max_length=32)),
                ('featured_image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
