# Generated by Django 4.1.3 on 2023-01-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
