# Generated by Django 4.1.3 on 2023-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articles_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
