# Generated by Django 4.1.3 on 2023-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_date_created_articles_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalltoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=55)),
                ('btn_url', models.CharField(max_length=255)),
            ],
        ),
    ]
