# Generated by Django 4.1.3 on 2023-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_calltoaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
